### ISSUE TITLE
【技術情報】ドメインシャーディング用ホスト名の試験公開

### ISSUE THREAD

**Issue by gsi-cyberjapan** [gsi-cyberjapan/vector-tile-experiment#6]
地理院タイルへのアクセスをドメインシャーディングの手法を用いて高速化するためのホスト名を試験公開いたします。詳細は、次のページをご覧ください。
https://github.com/gsi-cyberjapan/vector-tile-experiment/wiki/%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E3%82%B7%E3%83%A3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E7%94%A8%E3%83%9B%E3%82%B9%E3%83%88%E5%90%8D%EF%BC%88%E8%A9%A6%E9%A8%93%E5%85%AC%E9%96%8B%EF%BC%89
（平成26年9月1日　試験公開）

**Comment by johofukyu** [comment]
上記試験公開中のドメインは、令和3年12月20日14時をもって運用を停止いたします。
